services:
  android_1:
    image: redroid/redroid:11.0.0-latest
    container_name: android_1
    privileged: true
    ports:
      - "5555:5555"
    command:
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_fps=30
    environment:
      - ro.product.model=Pixel 5
      - ro.product.manufacturer=Google
      - ro.product.brand=google
      - ro.product.name=redfin
      - ro.product.device=redfin
      - ro.product.board=redfin
      - ro.build.flavor=redfin-user
      - ro.build.type=user
      - ro.build.tags=release-keys
      - ro.build.fingerprint=google/redfin/redfin:11/RQ3A.210805.001.A1/7474174:user/release-keys
      - ro.build.description=redfin-user 11 RQ3A.210805.001.A1 7474174 release-keys
      - ro.kernel.qemu=0
      - ro.hardware.egl=adreno
      - ro.hardware.vulkan=adreno
      # Отключаем встроенный root (su), чтобы Telegram его не спалил
      - redroid.prop.ro.secure=1
      - redroid.prop.ro.debuggable=0