services:
  android_1:
    image: redroid/redroid:11.0.0-latest
    container_name: android_1
    privileged: true
    ports:
      - "5555:5555"
    command:
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_fps=30
      # Оставляем только безопасную косметику для Telegram:
      - ro.product.model=Pixel 5
      - ro.product.manufacturer=Google
      - ro.product.brand=google