#!/usr/bin/env bash
# generate-env.sh — генерирует уникальные идентификаторы устройства
# перед каждым запуском docker compose up.
#
# Использование:
#   bash generate-env.sh [--instance 2]   # для второго инстанса
#   bash generate-env.sh                  # по умолчанию инстанс 1
#
# Формат .env: совместим с docker compose --env-file
set -euo pipefail

# ── ADB Key Check ─────────────────────────────────────────────────────────────
# Контейнер запускается с ro.secure=1 и требует pre-authorized публичный ключ.
# Файл должен быть на хосте по пути ~/.android/adbkey.pub перед первым запуском.
ADB_KEY_FILE="${HOME}/.android/adbkey.pub"
if [[ ! -f "${ADB_KEY_FILE}" ]]; then
  echo "WARNING: ADB public key not found at ${ADB_KEY_FILE}." >&2
  if command -v adb &>/dev/null; then
    echo "Generating ADB keys via 'adb devices'..." >&2
    adb devices >/dev/null 2>&1 || true
    if [[ -f "${ADB_KEY_FILE}" ]]; then
      echo "[OK] ADB keys generated: ${ADB_KEY_FILE}" >&2
    else
      echo "ERROR: Failed to generate ADB keys. Run 'adb devices' manually, then retry." >&2
      exit 1
    fi
  else
    echo "ERROR: 'adb' not found in PATH. Install Android SDK platform-tools and run 'adb devices'." >&2
    exit 1
  fi
else
  echo "[OK] ADB key found: ${ADB_KEY_FILE}"
fi

# ── Аргументы ────────────────────────────────────────────────────────────────
INSTANCE_ID=1
ENV_FILE=".env"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --instance) INSTANCE_ID="$2"; shift 2 ;;
    --out)      ENV_FILE="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

# ── Генерация идентификаторов ─────────────────────────────────────────────────

# DEVICE_SERIAL: 14 символов верхнего регистра (hex без дефисов)
#   Используем /dev/urandom как источник энтропии (нет зависимости от openssl)
DEVICE_SERIAL=$(
  LC_ALL=C tr -dc 'A-F0-9' < /dev/urandom | head -c 14
)

# DEVICE_BUILD_ID: формат RQ3A.YYMMDD.RAND (4 цифры)
RANDOM_SUFFIX=$(( RANDOM * RANDOM % 9000 + 1000 ))   # 1000–9999
DEVICE_BUILD_ID="RQ3A.$(date +%y%m%d).${RANDOM_SUFFIX}"

# ADB_PORT: базовый порт + смещение по номеру инстанса
BASE_ADB_PORT=5555
ADB_PORT=$(( BASE_ADB_PORT + (INSTANCE_ID - 1) * 10 ))

# ── Запись .env ───────────────────────────────────────────────────────────────

cat > "${ENV_FILE}" <<EOF
# Auto-generated by generate-env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Instance: ${INSTANCE_ID}

# Dynamic hardware identifiers
DEVICE_SERIAL=${DEVICE_SERIAL}
DEVICE_BUILD_ID=${DEVICE_BUILD_ID}

# ADB port (для init-device.sh)
ADB_PORT=${ADB_PORT}

# Proxy (переопредели при необходимости)
PROXY_URL=${PROXY_URL:-socks5://127.0.0.1:1080}

# Locale / timezone
SYS_TIMEZONE=${SYS_TIMEZONE:-Europe/Moscow}
SYS_LOCALE=${SYS_LOCALE:-ru-RU}

# SIM operator
SIM_NUMERIC=${SIM_NUMERIC:-25001}
SIM_ALPHA=${SIM_ALPHA:-MTS}
SIM_ISO=${SIM_ISO:-ru}
EOF

# ── Вывод ─────────────────────────────────────────────────────────────────────
echo "────────────────────────────────────────"
echo " Instance  : ${INSTANCE_ID}"
echo " Serial    : ${DEVICE_SERIAL}"
echo " Build ID  : ${DEVICE_BUILD_ID}"
echo " ADB port  : ${ADB_PORT}"
echo " Env file  : ${ENV_FILE}"
echo "────────────────────────────────────────"
echo "[OK] .env файл создан."
