# Используем актуальный образ ReDroid с Magisk и NDK (ARM-транслятор)
FROM abing7k/redroid:a11_magisk_ndk_amd

# Просто копируем наш скрипт инициализации хуков внутрь Android
# Утилиты curl и unzip уже есть внутри Android "из коробки"
COPY setup-hooks.sh /data/setup-hooks.sh