# Используем актуальный образ ReDroid с Magisk и поддержкой ARM-трансляции (NDK)
FROM abing7k/redroid:a11_magisk_ndk_amd

# Устанавливаем утилиты для скачивания модулей
RUN apt-get update && apt-get install -y curl unzip && rm -rf /var/lib/apt/lists/*

# Копируем скрипт инициализации хуков
COPY setup-hooks.sh /data/setup-hooks.sh
RUN chmod +x /data/setup-hooks.sh